services:
  models-varroa-on-bee:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8752:8752"
    environment:
      - PORT=8752
      - MODEL_WEIGHTS=/app/yolo11n.pt
    restart: always
